# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opendatasoft_automation.models.http_connection import HTTPConnection

class TestHTTPConnection(unittest.TestCase):
    """HTTPConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTTPConnection:
        """Test HTTPConnection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HTTPConnection`
        """
        model = HTTPConnection()
        if include_optional:
            return HTTPConnection(
                url = 'https://my-server.com',
                headers = [
                    opendatasoft_automation.models.http_connection_all_of_headers.HTTPConnection_allOf_headers(
                        name = 'header-name', 
                        value = 'header-value', )
                    ],
                auth = opendatasoft_automation.models.http_auth.HTTPAuth(
                    type = '0', )
            )
        else:
            return HTTPConnection(
                url = 'https://my-server.com',
        )
        """

    def testHTTPConnection(self):
        """Test HTTPConnection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
