# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opendatasoft_automation.models.aws_signature_v4_auth import AWSSignatureV4Auth

class TestAWSSignatureV4Auth(unittest.TestCase):
    """AWSSignatureV4Auth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AWSSignatureV4Auth:
        """Test AWSSignatureV4Auth
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AWSSignatureV4Auth`
        """
        model = AWSSignatureV4Auth()
        if include_optional:
            return AWSSignatureV4Auth(
                access_key_id = '',
                secret_access_key = '',
                region = ''
            )
        else:
            return AWSSignatureV4Auth(
                access_key_id = '',
                secret_access_key = '',
                region = '',
        )
        """

    def testAWSSignatureV4Auth(self):
        """Test AWSSignatureV4Auth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
