# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opendatasoft_automation.models.snowflake_odbc_datasource_all_of_connection import SnowflakeODBCDatasourceAllOfConnection

class TestSnowflakeODBCDatasourceAllOfConnection(unittest.TestCase):
    """SnowflakeODBCDatasourceAllOfConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnowflakeODBCDatasourceAllOfConnection:
        """Test SnowflakeODBCDatasourceAllOfConnection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnowflakeODBCDatasourceAllOfConnection`
        """
        model = SnowflakeODBCDatasourceAllOfConnection()
        if include_optional:
            return SnowflakeODBCDatasourceAllOfConnection(
                type = 'snowflake_odbc',
                connection_string = '',
                uid = ''
            )
        else:
            return SnowflakeODBCDatasourceAllOfConnection(
                type = 'snowflake_odbc',
                connection_string = '',
                uid = '',
        )
        """

    def testSnowflakeODBCDatasourceAllOfConnection(self):
        """Test SnowflakeODBCDatasourceAllOfConnection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
