# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opendatasoft_automation.models.list_images200_response import ListImages200Response

class TestListImages200Response(unittest.TestCase):
    """ListImages200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListImages200Response:
        """Test ListImages200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListImages200Response`
        """
        model = ListImages200Response()
        if include_optional:
            return ListImages200Response(
                total_count = '',
                next = '',
                previous = '',
                results = [
                    opendatasoft_automation.models.list_images_200_response_all_of_results_inner.list_images_200_response_allOf_results_inner(
                        url = '/assets/theme_image/Acronym-Turquoise.svg', )
                    ]
            )
        else:
            return ListImages200Response(
        )
        """

    def testListImages200Response(self):
        """Test ListImages200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
