# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opendatasoft_automation.models.ftp_datasource import FTPDatasource

class TestFTPDatasource(unittest.TestCase):
    """FTPDatasource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FTPDatasource:
        """Test FTPDatasource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FTPDatasource`
        """
        model = FTPDatasource()
        if include_optional:
            return FTPDatasource(
                relative_url = '',
                connection = None
            )
        else:
            return FTPDatasource(
                connection = None,
        )
        """

    def testFTPDatasource(self):
        """Test FTPDatasource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
