# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.amazon_s3_connection import AmazonS3Connection

class TestAmazonS3Connection(unittest.TestCase):
    """AmazonS3Connection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AmazonS3Connection:
        """Test AmazonS3Connection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AmazonS3Connection`
        """
        model = AmazonS3Connection()
        if include_optional:
            return AmazonS3Connection(
                headers = [
                    openapi_client.models.http_connection_all_of_headers.HTTPConnection_allOf_headers(
                        name = 'header-name', 
                        value = 'header-value', )
                    ],
                auth = {"type":"aws_signature_v4","region":"eu-west-1","access_key_id":"access_key_id","secret_access_key":"secret_access_key"}
            )
        else:
            return AmazonS3Connection(
        )
        """

    def testAmazonS3Connection(self):
        """Test AmazonS3Connection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
