# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.guess_unsaved_resource_extractor_params_request import GuessUnsavedResourceExtractorParamsRequest

class TestGuessUnsavedResourceExtractorParamsRequest(unittest.TestCase):
    """GuessUnsavedResourceExtractorParamsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GuessUnsavedResourceExtractorParamsRequest:
        """Test GuessUnsavedResourceExtractorParamsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GuessUnsavedResourceExtractorParamsRequest`
        """
        model = GuessUnsavedResourceExtractorParamsRequest()
        if include_optional:
            return GuessUnsavedResourceExtractorParamsRequest(
                datasource = {"type":"http","connection":{"type":"http","url":"https://my-server.com","auth":null},"headers":[{"name":"header-name","value":"header-value"}],"relative_url":"/fromages.csv"},
                type = 'csvfile'
            )
        else:
            return GuessUnsavedResourceExtractorParamsRequest(
                datasource = {"type":"http","connection":{"type":"http","url":"https://my-server.com","auth":null},"headers":[{"name":"header-name","value":"header-value"}],"relative_url":"/fromages.csv"},
                type = 'csvfile',
        )
        """

    def testGuessUnsavedResourceExtractorParamsRequest(self):
        """Test GuessUnsavedResourceExtractorParamsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
