# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opendatasoft_automation.models.inline_object4 import InlineObject4

class TestInlineObject4(unittest.TestCase):
    """InlineObject4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineObject4:
        """Test InlineObject4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineObject4`
        """
        model = InlineObject4()
        if include_optional:
            return InlineObject4(
                error_code = 'invalid_dataset_status',
                message = '0'
            )
        else:
            return InlineObject4(
                error_code = 'invalid_dataset_status',
                message = '0',
        )
        """

    def testInlineObject4(self):
        """Test InlineObject4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
