# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_code_editor_page_user_security200_response import ListCodeEditorPageUserSecurity200Response

class TestListCodeEditorPageUserSecurity200Response(unittest.TestCase):
    """ListCodeEditorPageUserSecurity200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCodeEditorPageUserSecurity200Response:
        """Test ListCodeEditorPageUserSecurity200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCodeEditorPageUserSecurity200Response`
        """
        model = ListCodeEditorPageUserSecurity200Response()
        if include_optional:
            return ListCodeEditorPageUserSecurity200Response(
                total_count = 56,
                next = '',
                previous = '',
                results = [
                    openapi_client.models.user_ruleset.User ruleset(
                        user = openapi_client.models.related_user.Related user(
                            username = 'louise.data', ), 
                        permissions = [
                            'edit_page'
                            ], )
                    ]
            )
        else:
            return ListCodeEditorPageUserSecurity200Response(
        )
        """

    def testListCodeEditorPageUserSecurity200Response(self):
        """Test ListCodeEditorPageUserSecurity200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
