# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.abort_harvester400_response import AbortHarvester400Response

class TestAbortHarvester400Response(unittest.TestCase):
    """AbortHarvester400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AbortHarvester400Response:
        """Test AbortHarvester400Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AbortHarvester400Response`
        """
        model = AbortHarvester400Response()
        if include_optional:
            return AbortHarvester400Response(
                error_code = 'invalid_harvester_status',
                message = '0'
            )
        else:
            return AbortHarvester400Response(
                error_code = 'invalid_harvester_status',
                message = '0',
        )
        """

    def testAbortHarvester400Response(self):
        """Test AbortHarvester400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
