# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opendatasoft_automation.models.inline_object5_records_errors_inner import InlineObject5RecordsErrorsInner

class TestInlineObject5RecordsErrorsInner(unittest.TestCase):
    """InlineObject5RecordsErrorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineObject5RecordsErrorsInner:
        """Test InlineObject5RecordsErrorsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineObject5RecordsErrorsInner`
        """
        model = InlineObject5RecordsErrorsInner()
        if include_optional:
            return InlineObject5RecordsErrorsInner(
                record_id = '',
                field_uid = '',
                processor_uid = '',
                message = ''
            )
        else:
            return InlineObject5RecordsErrorsInner(
        )
        """

    def testInlineObject5RecordsErrorsInner(self):
        """Test InlineObject5RecordsErrorsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
