# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.resource_unsaved_preview200_response import ResourceUnsavedPreview200Response

class TestResourceUnsavedPreview200Response(unittest.TestCase):
    """ResourceUnsavedPreview200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceUnsavedPreview200Response:
        """Test ResourceUnsavedPreview200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceUnsavedPreview200Response`
        """
        model = ResourceUnsavedPreview200Response()
        if include_optional:
            return ResourceUnsavedPreview200Response(
                fields = [
                    openapi_client.models.resource_unsaved_preview_200_response_fields_inner.resource_unsaved_preview_200_response_fields_inner(
                        description = '', 
                        original_name = '', 
                        label = '', 
                        type = '', 
                        annotations = [
                            openapi_client.models.resource_unsaved_preview_200_response_fields_inner_annotations_inner.resource_unsaved_preview_200_response_fields_inner_annotations_inner(
                                name = '', 
                                args = [
                                    ''
                                    ], )
                            ], 
                        name = '', )
                    ],
                records = [
                    None
                    ]
            )
        else:
            return ResourceUnsavedPreview200Response(
        )
        """

    def testResourceUnsavedPreview200Response(self):
        """Test ResourceUnsavedPreview200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
