# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opendatasoft_automation.models.user_security2 import UserSecurity2

class TestUserSecurity2(unittest.TestCase):
    """UserSecurity2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSecurity2:
        """Test UserSecurity2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSecurity2`
        """
        model = UserSecurity2()
        if include_optional:
            return UserSecurity2(
                user = opendatasoft_automation.models.related_user.Related user(
                    username = 'louise.data', ),
                permissions = [
                    'edit_page'
                    ]
            )
        else:
            return UserSecurity2(
        )
        """

    def testUserSecurity2(self):
        """Test UserSecurity2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
