# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opendatasoft_automation.models.update_dataset404_response import UpdateDataset404Response

class TestUpdateDataset404Response(unittest.TestCase):
    """UpdateDataset404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateDataset404Response:
        """Test UpdateDataset404Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateDataset404Response`
        """
        model = UpdateDataset404Response()
        if include_optional:
            return UpdateDataset404Response(
                error_code = 'not_found',
                message = '0'
            )
        else:
            return UpdateDataset404Response(
                error_code = 'not_found',
                message = '0',
        )
        """

    def testUpdateDataset404Response(self):
        """Test UpdateDataset404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
