# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from opendatasoft_automation.models.amazon_s3_auth import AmazonS3Auth
from typing import Optional, Set
from typing_extensions import Self

class AmazonS3AWSIAMRoleAuth(AmazonS3Auth):
    """
    AmazonS3AWSIAMRoleAuth
    """ # noqa: E501
    ods_aws_account_id: Optional[StrictStr] = Field(default=None, description="The AWS account number that will assume the role.")
    external_id: Optional[StrictStr] = Field(default=None, description="The identifier for the connection that will assume the role.")
    is_valid: Optional[StrictBool] = Field(default=None, description="The capability of assuming the role for the connection. Is set to true if the role is successfully assumed when the \"role_arn\" is set.")
    role_arn: Optional[StrictStr] = Field(default=None, description="The identifier of the role to be assumed should be set to an empty string when the connection is created. It is expected to be updated by the user.")
    region: StrictStr
    __properties: ClassVar[List[str]] = ["type", "ods_aws_account_id", "external_id", "is_valid", "role_arn", "region"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AmazonS3AWSIAMRoleAuth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "ods_aws_account_id",
            "external_id",
            "is_valid",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AmazonS3AWSIAMRoleAuth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "ods_aws_account_id": obj.get("ods_aws_account_id"),
            "external_id": obj.get("external_id"),
            "is_valid": obj.get("is_valid"),
            "role_arn": obj.get("role_arn"),
            "region": obj.get("region")
        })
        return _obj


