# coding: utf-8

"""
    Opendatasoft's Automation API Documentation

    Opendatasoft REST API to manage your portal and its catalog

    The version of the OpenAPI document: 1.0
    Contact: support@opendatasoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.http_auth import HTTPAuth
from typing import Optional, Set
from typing_extensions import Self

class HTTPOAuth2Auth(HTTPAuth):
    """
    HTTPOAuth2Auth
    """ # noqa: E501
    client_id: StrictStr
    client_secret: StrictStr
    scope: StrictStr
    token_endpoint: StrictStr
    grant_type: StrictStr
    username: Optional[StrictStr] = None
    password: Optional[StrictStr] = None
    code: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["type", "client_id", "client_secret", "scope", "token_endpoint", "grant_type", "username", "password", "code"]

    @field_validator('grant_type')
    def grant_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['password', 'authorization_code', 'client_credentials']):
            raise ValueError("must be one of enum values ('password', 'authorization_code', 'client_credentials')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HTTPOAuth2Auth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HTTPOAuth2Auth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "client_id": obj.get("client_id"),
            "client_secret": obj.get("client_secret"),
            "scope": obj.get("scope"),
            "token_endpoint": obj.get("token_endpoint"),
            "grant_type": obj.get("grant_type"),
            "username": obj.get("username"),
            "password": obj.get("password"),
            "code": obj.get("code")
        })
        return _obj


